on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      - name: Checkout
        uses: actions/checkout@v2
      - name: Action step
        uses: ./ # Uses an action in the root directory
        id: hello
